name: Meterian scan workflow

on: push

jobs:
    meterian_scan:
        name: Meterian client scan
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v2
          - name: Scan project with the Meterian client
            uses: MeterianHQ/meterian-github-action@autofix-prs-and-issues
            env:
              GITHUB_TOKEN: ${{ github.token }}
              CLIENT_CANARY_FLAG: "--canary" #temporary using canary version of the cli
              METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
            with:
                autofix: 'conservative+vulns,safe+all'
                cli_args: "--project-url=tmp/log4j-vuln-coverage-check"
          - name: Print report.json
            run: cat report.json
